{
 "title": "Pipeline Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "cluster capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cluster capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "cluster:capacity_cpu_cores:sum", "legendFormat": "__auto" },
    { "expr": "cluster:memory_usage_bytes:sum", "legendFormat": "__auto" }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "datasource" },
  {
   "title": "Tekton Scheduling Overhead",
   "type": "stat",
   "description": "The ratio of time needed for the Tekton controller to start processing a PipelineRun after its creation vs. the time needed to execute successful PipelineRuns",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pipeline_service_schedule_overhead_percentage_sum{status='succeded'}[30m])) / sum(increase(pipeline_service_schedule_overhead_percentage_count{status='succeded'}[30m]))"
    }
   ]
  },
  {
   "title": "Tekton Execution Overhead",
   "type": "stat",
   "description": "Time gaps between TaskRuns relative to the overall duration of successful PipelineRuns",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pipeline_service_execution_overhead_percentage_sum{status='succeded'}[30m])) / sum(increase(pipeline_service_execution_overhead_percentage_count{status='succeded'}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PipelineRun and TaskRun Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "PipelineRuns Per Hour",
     "type": "graph",
     "description": "Completed PipelineRuns per hour",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (rate(tekton_pipelines_controller_pipelinerun_count[1h]))* 3600"
      }
     ]
    },
    {
     "title": "PipelineRun Success",
     "type": "stat",
     "description": "PipelineRun success per hour",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate(tekton_pipelines_controller_pipelinerun_count{status=\"success\"}[1h])) / sum (rate(tekton_pipelines_controller_pipelinerun_count[1h]))"
      }
     ]
    },
    {
     "title": "TaskRuns Per Hour",
     "type": "graph",
     "description": "Completed TaskRuns Per Hour",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (rate(tekton_pipelines_controller_taskrun_count[1h]))* 3600"
      }
     ]
    },
    {
     "title": "TaskRun Success",
     "type": "stat",
     "description": "TaskRun success per hour",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate(tekton_pipelines_controller_taskrun_count{status=\"success\"}[1h])) / sum (rate(tekton_pipelines_controller_taskrun_count[1h]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipelines-Controller Resource Utlization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Total average CPU usage of the Pipelines.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"tekton-pipelines-controller-.*\", namespace=\"openshift-pipelines\", container=\"\"}[5m]))"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "description": "Working set memory usage of Pipelines Controller Containers ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"tekton-pipelines-controller-.*\", namespace=\"openshift-pipelines\", container=\"\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipelines Controller Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Pipelineruns Running",
     "type": "stat",
     "description": "Number of Pipelineruns executing currently",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tekton_pipelines_controller_running_pipelineruns_count{prometheus=\"openshift-user-workload-monitoring/user-workload\"}"
      }
     ]
    },
    {
     "title": "Taskruns Running",
     "type": "stat",
     "description": "Number of Taskruns executing currently",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tekton_pipelines_controller_running_taskruns_count{prometheus=\"openshift-user-workload-monitoring/user-workload\"}"
      }
     ]
    },
    {
     "title": "Pipelines Controller Container Restarts",
     "type": "graph",
     "description": "Frequency of Pipelines Controller restarts (This is experimental and may be removed in future)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\", pod=~\"tekton-pipelines-controller-.*\"}[7d])"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "description": "The workqueue for the Tekton Pipelines Reconcilers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(tekton_pipelines_controller_workqueue_depth)"
      }
     ]
    },
    {
     "title": "Taskruns Throttled by Node",
     "type": "graph",
     "description": "Number of taskruns executing currently whose underlying Pods or Containers are suspended by k8s because of Node level constraints",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tekton_pipelines_controller_running_taskruns_throttled_by_node_count"
      }
     ]
    },
    {
     "title": "Pipelines Client Results",
     "type": "timeseries",
     "description": "Total number of Kubernetes API requests by Tekton Controller",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(tekton_pipelines_controller_client_results{prometheus=\"openshift-user-workload-monitoring/user-workload\"}[1h])*3600"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipelines Performance Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Average duration of successful pipelineruns",
     "type": "bargauge",
     "description": "Average duration of successful Pipelineruns in seconds over one hour time window grouped by namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) ((avg_over_time(tekton_pipelines_controller_pipelinerun_duration_seconds_sum{status=\"success\"}[1h]) / avg_over_time(tekton_pipelines_controller_pipelinerun_duration_seconds_count{status=\"success\"}[1h])))"
      }
     ]
    },
    {
     "title": "Average time for learning of pipelinerun creation",
     "type": "bargauge",
     "description": "Average time for learning of pipelinerun creation in seconds for each namespace over the last 1 hour",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) ((avg_over_time(pipelinerun_duration_scheduled_seconds_sum[1h]) / avg_over_time(pipelinerun_duration_scheduled_seconds_count[1h])))"
      }
     ]
    },
    {
     "title": "Average duration of pipelinerunpods",
     "type": "bargauge",
     "description": "Average duration of the pods ultimately launched from PipelineRuns, using a descending sort and grouped by namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc((sum by (namespace) (tekton_pods_create_to_complete_seconds_sum / tekton_pods_create_to_complete_seconds_count)) / (sum by (namespace) (tekton_pipelines_controller_pipelinerun_duration_seconds_count)))"
      }
     ]
    },
    {
     "title": "Average time for the kubelet to mark pipelinerun pods schedulable",
     "type": "bargauge",
     "description": "Average time for the kubelet to mark pipelinerun pods schedulable, using a descending sort and grouped by namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc((sum by (namespace) (taskrun_pod_duration_kubelet_acknowledged_milliseconds_sum / taskrun_pod_duration_kubelet_acknowledged_milliseconds_count / 1000)) / (sum by (namespace) (tekton_pipelines_controller_pipelinerun_duration_seconds_count)))"
      }
     ]
    },
    {
     "title": "Average time for the kubelet's pulling of images and starting pipelinerun containers",
     "type": "bargauge",
     "description": "Average time for the kubelet's pulling of images and starting pipelinerun containers, using a descending sort and grouped by namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc((sum by (namespace) (taskrun_pod_duration_kubelet_to_container_start_milliseconds_sum / taskrun_pod_duration_kubelet_to_container_start_milliseconds_count / 1000)) / (sum by (namespace) (tekton_pipelines_controller_pipelinerun_duration_seconds_count)))"
      }
     ]
    },
    {
     "title": "Average pipelinerun pod durations by task, namespace",
     "type": "bargauge",
     "description": "Average pipelinerun pod durations by task, namespace, using a descending sort and grouped by task and namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc((avg by (taskname,namespace) (tekton_pods_create_to_complete_seconds_sum / tekton_pods_create_to_complete_seconds_count)))"
      }
     ]
    },
    {
     "title": "Taskruns Throttled by Quota",
     "type": "graph",
     "description": "Number of taskruns executing currently whose underlying Pods or Containers are suspended by k8s because of defined ResourceQuotas",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tekton_pipelines_controller_running_taskruns_throttled_by_quota_count"
      }
     ]
    },
    {
     "title": "Taskruns Throttled by Node",
     "type": "graph",
     "description": "Number of taskruns executing currently whose underlying Pods or Containers are suspended by k8s because of Node level constraints",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tekton_pipelines_controller_running_taskruns_throttled_by_node_count"
      }
     ]
    },
    {
     "title": "PIpelineruns failed by PVC Quota",
     "type": "graph",
     "description": "Number of pipelineruns whose pods could not be started because of PVC quotas.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pipelinerun_failed_by_pvc_quota_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipelines-as-code Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Total average CPU usage of the Pipelines-as-code watcher and controller pods over the past hour.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"pipelines-as-code-(watcher|controller)-.*\", namespace=\"openshift-pipelines\", container=\"\"}[5m]))*100"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Working set memory usage of Pipelines-as-code watcher and controller pods over the past hour.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (container_memory_working_set_bytes{pod=~\"pipelines-as-code-(watcher|controller)-.*\", namespace=\"openshift-pipelines\", container=\"\"})"
      }
     ]
    },
    {
     "title": "PipelineRuns Watched Per Hour",
     "type": "graph",
     "description": "Number of Pipelineruns watched on pull_request and push events",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (event_type) (rate(pac_watcher_pipelines_as_code_pipelinerun_count{prometheus=\"openshift-user-workload-monitoring/user-workload\"}[1h]))*3600"
      }
     ]
    },
    {
     "title": "Watcher Workqueue Depth",
     "type": "graph",
     "description": "The workqueue depth for the Pipelines-as-code Reconcilers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(pac_watcher_workqueue_depth)"
      }
     ]
    },
    {
     "title": "Watcher Client Results",
     "type": "graph",
     "description": "Total number of kubernetes api request for pipelines-as-code watcher",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pac_watcher_client_results{prometheus=\"openshift-user-workload-monitoring/user-workload\"}[1h])*3600"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics Exporter Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workqueue Depth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "workqueue_depth{namespace='openshift-pipelines',pod=~'pipeline-metrics-exporter.+'}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='openshift-pipelines',pod=~'pipeline-metrics-exporter-.*', container=\"\"}[5m]))"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace='openshift-pipelines',pod=~'pipeline-metrics-exporter-.*', container=\"\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Tekton Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Status",
     "type": "stat",
     "description": "Status of API and Watcher",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{job=\"tekton-results-api\"})",
       "legendFormat": "API"
      },
      {
       "expr": "sum(up{job=\"tekton-results-watcher\"})",
       "legendFormat": "Watcher"
      }
     ]
    },
    {
     "title": "API Success Rate",
     "type": "stat",
     "description": "Request success rate",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1 - ((sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code=~\"Internal|Unavailable|Unknown|Unimplemented\"}[$__rate_interval]))) / sum(rate(grpc_server_started_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\"}[$__rate_interval])))\n",
       "legendFormat": "Success Rate"
      }
     ]
    },
    {
     "title": "Watcher Work Queue Depth",
     "type": "stat",
     "description": "Watcher work queue depth",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(watcher_workqueue_depth{job=\"tekton-results-watcher\"})",
       "legendFormat": "Queue Depth"
      }
     ]
    },
    {
     "title": "API Request Rate",
     "type": "stat",
     "description": "Requests/Second",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\"}[$__rate_interval]))",
       "legendFormat": "Request Rate"
      }
     ]
    },
    {
     "title": "API Request Latency",
     "type": "stat",
     "description": "Request latency 99%-tile",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\"}[$__rate_interval])) by (le) )",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Watcher Reconcile Latency",
     "type": "stat",
     "description": "Reconcile latency 99%-tile - \nLatency of reconcile operations.",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(watcher_reconcile_latency_bucket{job=\"tekton-results-watcher\"}[$__rate_interval])) by (le) )",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Container CPU Utilisation",
     "type": "timeseries",
     "description": "Pod CPU utilisation ",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"tekton-results-api-.*\", namespace=\"tekton-results\", container=\"\"}[$__rate_interval]))",
       "legendFormat": "API Server"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"tekton-results-watcher-.*\", namespace=\"tekton-results\", container=\"\"}[$__rate_interval]))",
       "legendFormat": "Watcher"
      }
     ]
    },
    {
     "title": "Container Memory Utilisation",
     "type": "timeseries",
     "description": "Pod memory utilisation",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"tekton-results-api-.*\",namespace=\"tekton-results\", container=\"\"})",
       "legendFormat": "API Server"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"tekton-results-watcher-.*\",namespace=\"tekton-results\", container=\"\"})",
       "legendFormat": "Watcher"
      }
     ]
    },
    {
     "title": "API Response Rate",
     "type": "timeseries",
     "description": "RPC execution rate",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\"}[$__rate_interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "API Latency Distribution",
     "type": "heatmap",
     "description": "Latency Distribution",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handling_seconds_bucket{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "API Server Errors",
     "type": "timeseries",
     "description": "Server error distribution across gRPC methods.               \nStatus Codes:\nInternal, Unavailable, Unknown, Unimplemented",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code!=\"OK\"}[$__rate_interval])) by (grpc_method)",
       "legendFormat": "RPC: {{grpc_method}}"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code=~\"Internal|Unavailable|Unknown|Unimplemented\"}[$__rate_interval])) by (grpc_code) / ignoring(grpc_code) group_left sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code!=\"OK\"}[$__rate_interval]))",
       "legendFormat": "Error: {{grpc_code}}"
      }
     ]
    },
    {
     "title": "API Other Errors",
     "type": "timeseries",
     "description": "Other error distribution across gRPC methods.           \nStatus Codes Except:\nInternal, Unavailable, Unknown, Unimplemented",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code!=\"OK\"}[$__rate_interval])) by (grpc_method)",
       "legendFormat": "RPC: {{grpc_method}}"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code!~\"Internal|Unavailable|Unknown|Unimplemented\"}[$__rate_interval])) by (grpc_code) / ignoring(grpc_code) group_left sum(rate(grpc_server_handled_total{job=\"tekton-results-api\", grpc_service=~\"tekton.results.v1alpha2.*\", grpc_code!=\"OK\"}[$__rate_interval]))",
       "legendFormat": "Error: {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Watcher Reconcile Rate",
     "type": "timeseries",
     "description": "Number of reconcile operations",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(watcher_reconcile_count{job=\"tekton-results-watcher\"}[$__rate_interval])) by (success)",
       "legendFormat": "{{success}}"
      }
     ]
    },
    {
     "title": "Watcher Latency",
     "type": "timeseries",
     "description": "Work queue latency at queue depth",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(watcher_workqueue_queue_latency_seconds_count{job=\"tekton-results-watcher\"}[$__rate_interval]))",
       "legendFormat": "Queue Latency"
      },
      {
       "expr": "sum(rate(watcher_reconcile_latency_count{job=\"tekton-results-watcher\"}[$__rate_interval]))",
       "legendFormat": "Reconcile Latency"
      },
      {
       "expr": "sum(watcher_work_queue_depth{job=\"tekton-results-watcher\"})",
       "legendFormat": "Queue Depth"
      }
     ]
    }
   ]
  },
  {
   "title": "Tekton Chains",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Tekton Chains CPU Fraction Use",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "rate(watcher_go_gc_cpu_fraction{app=\"tekton-chains-controller\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tekton Chains Workqueue Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "rate(watcher_workqueue_longest_running_processor_seconds_count{app=\"tekton-chains-controller\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sprayproxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(sprayproxy_http_inbound_requests_total{namespace=\"sprayproxy\"}[5m]) * 300",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Forwarded Requests",
     "type": "timeseries",
     "description": "Forwarded attempts to backend server(s)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "rate(sprayproxy_http_forwarded_requests_total[5m]) * 300",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response Time Duration",
     "type": "bargauge",
     "description": "Forwarded request duration in seconds",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(sprayproxy_http_response_time_duration_seconds_bucket[5m]) * 300",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}